version: "3.9"
services:
  app:
    build: . 
    command: pnpm dev 
    working_dir: /app
    volumes:
      - .:/app 
    ports:
      - "3000:3000"
    depends_on:
      - db 
      - redis 
  
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: dev 
      POSTGRES_PASSWORD: dev 
      POSTGRES_DB: devdb 
    ports:
      - "5432:5432" 

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

