version: "3.9"

services:
  app:
    # Не пересобираем образ при каждом изменении
    # Используем локальный node_modules + hot-reload
    volumes:
      - .:/usr/src/app:cached
      - /usr/src/app/node_modules
    command: sh -c "npm install && npm run dev"
    environment:
      NODE_ENV: development
      NEXT_TELEMETRY_DISABLED: 1
    ports:
      - "3000:3000"
    depends_on:
      - db
